import pandas as ps
df=ps.read_excel('C:/eya/Classe.xlsx')
print(df)
print(df.shape)
print(df.describe)
print(df.size)
print(df.iloc[0,4])
print(df.iloc[2])
print(df.tail(2))
print(df.head(2))
print(df.info())
print(df.columns)
print(df.iloc[:3])
print(df.Moyenne)
df.loc[0,'Nom']="Hedi"
print(df)
df.loc[3,'Moyenne']=20
print(df)
df.loc[5]=['Eya','Atia',18,18,'femme']
print(df)
df=df.drop([1])
print(df)
df=df.drop(['Moyenne'],axis=1)
print(df)
print(df.Nom)
df['statut']=['majeur','mineur','majeur','mineur','majeur','mineur']
print(df)
df.rename(columns={'Moyenne':'Note'},inplace=True)
print(df)
print(df[['Nom','Moyenne']])
print(df.Nom[0:2],df.Moyenne[0:2])
print(df.iloc[0:3,[1,3]])
a=df['Moyenne'].min()
print(a)
b=df['Moyenne'].max()
print(b)
c=df['Moyenne'].mean()
print(c)
d=df['Moyenne'].sum()
print(d)
e=df['Moyenne'].count()
print(e)
print(df[df['Moyenne']>=10])
print(df[(df['Moyenne']>=10) & (df['Age']<18)])
df=df.sort_index(axis=1)
print(df)
df=df.sort_index()
print(df)
df=df.sort_values(by=['Nom','Prenom'],ascending=True)
print(df)
#'''
# import matplotlib.pyplot as plt
# df.plot.line(x='Nom',y='Moyenne',title='Moyenne par Eleve',color='blue')
# plt.show()
